# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
	dependencies = [
		('comments', '0002_auto_20170729_2007'),
	]

	operations = [
		migrations.AddField(
			model_name='comment',
			name='text',
			field=models.TextField(default=django.utils.timezone.now),
			preserve_default=False,
		),
	]
